
spring:
  datasource:
    url: jdbc:mysql://134.175.221.21:3306/userdatadb
    username: userdatadb
    password: 123456
mymqtt:
  HOST: tcp://134.175.221.21:1883
  clientId: ${random.uuid}
  qos: 0
