#spring.datasource.url=jdbc:mysql://134.175.221.21:3306/a
#
#spring.datasource.username=you
#spring.datasource.password=123456
#
#spring.datasource.max-idle=10
#spring.datasource.max-wait=10000
#spring.datasource.min-idle=5
#spring.datasource.initial-size=5
spring:
  datasource:
    url: jdbc:mysql://134.175.221.21:3306/userdatadb
    username: userdatadb
    password: 123456
#    max-idle: 10
#    max-wait-millis: 10000
#    min-idle: 5
#    initial-size: 5